#! /bin/bash
SOURCE_DIR=$(cd `dirname $0`; pwd)
CMAKE_BUILD_DIR=${SOURCE_DIR}/build
CMAKE_GENERATOR="Xcode"
CMAKE_BUILD_TYPE="Debug"
CMAKE_DEBUG_OUTPUT=${SOURCE_DIR}/bin/mac
CMAKE_RUNTIME_OUTPUT=${SOURCE_DIR}/bin/mac

mkdir -p ${CMAKE_BUILD_DIR}
cd ${CMAKE_BUILD_DIR}

cmake -G ${CMAKE_GENERATOR} \
	-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} \
    -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG=${CMAKE_DEBUG_OUTPUT} \
    -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=${CMAKE_RUNTIME_OUTPUT} \
    -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO=${CMAKE_RUNTIME_OUTPUT} \
    -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE=${CMAKE_RUNTIME_OUTPUT} \
    -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_MINSIZEREL=${CMAKE_RUNTIME_OUTPUT} \
    ${SOURCE_DIR}
